name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: run sheel script
        run: | 
             stringPhrases=("Linux" "is a free" "open-source" "operating system")
             len=${#stringPhrases[@]}
             counter=1 ;
            
             for i in "${stringPhrases[@]}"
                 do
                   if [$counter eq $len] then
                  echo "counter $counter $i";
                   fi  
                
                  counter=$((counter+1))
                 
                  done
