name:  workflowd
on: workflow_dispatch
jobs:
  first-job:
    runs-on unbuntu-latest
      steps:
        -name:firststep
         run: echo 'hello'
        -name:steps2
         run: echo 'hello2'
         
