name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: run sheel script
        run: | 
             stringPhrases=("Linux" "is a free" "open-source" "operating system")
             len=${#stringPhrases[@]}
             
             for((i=1; i<$len; i++))
                 do
                    echo "counter [$i -eq $len )]"
                    if [ $i -eq $len]; then
                       echo "String: ${stringPhrases[$i+1]}"
                    else
                      echo "You are not root"
                     fi
                 
                  done
