# This is a basic workflow to help you get started with Actions

name: Build Liquibase setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  #push:
  #  branches: [ "dev" ]
  #pull_request:
  #  branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    # ${SQLCL_HOME}/bin/sql svy/SVYEXA3@exa5-scan.fdny.org:1724/HRIS_TST.FDNY.ORG
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: gvenzl/setup-oracle-sqlcl@v1.0.0
      - name: Run SQL Command
        run: |
             echo "SELECT 'hey' ;" | SQL
   
